### ISSUE TITLE
Support for formatters

### ISSUE THREAD

**Issue by LakshithadeSilva** [kaizenplatform/fluent-plugin-bigquery#141]
Hi there :)

I was wondering if you could enhance this plugin with the ability to support formatters.

The simple use case is that anyone who wish to send data to BigQuery in the Avro format is unable to do at the moment. There's already an Avro formatter plugin but that plugin cannot be used together with this plugin.

Thank you and best  wishes,
Luki

**Comment by joker1007** [comment]
I can support formatter plugin, but have a probrem.
fluent-plugin-bigquery has `insert` and `load` modes.
And buffering format is shared, but `insert` and `load` API format is actually different.
In current version, format is based on `load` API spec. 
This plugin parse buffered data and convert data to `insert` API format by itself.
Because user can handle error files easily.

For example, a fluentd config has seconday output section and Bigquery API is down, fluentd output buffered data to local file as it is.
If secondary output plugin format is same with one of `load` API spec, user can retry to load by bq Command-line Tool.

For the above reasons, I don't support formatter plugin currently.
But it may be able to support for only  `load` mode.

**Comment by LakshithadeSilva** [comment]
Thank you so much for the reply with all the details.

I understand the problem with the different API formats of `insert` and `load` modes. 
I think you decision to use the `load` API format for the buffering makes good sense.

If you can, it would be a good to support formatter plugin for the only `load` mode.
This wont be a problem because BigQuery API currently supports different API formats for the `load` mode only. The `insert` mode accepts only the JSON format.
Supporting formatter plugin for `load` will be very useful for me :)

Thank you.

**Comment by LakshithadeSilva** [comment]
Hi there,

Thank you very much for accepting my request and supporting formatters in this plugin. Your help is much appreciated.

Kind regards.
