### ISSUE TITLE
Dynamic table name assign support

### ISSUE THREAD

**Issue by foremap** [kaizenplatform/fluent-plugin-bigquery#19]
I saw the plugin could support the table name with the time format a few days ago. 
But sometimes the time format table name maybe not enough.  
Is it possible let plugin read table name by the fields? 
For example :  
                          table   accesslog_%Y_%m_%{name}

"name" is one of the fileds in fluentd.

**Comment by GLStephen** [comment]
I know that exploring a data/field driven approach to tables would help many use cases tremendously. It is worth exploring and is not quite the same as what is provided by plugin forest. For instance, in a multi-tenant system data may be ingested with a value indicating the customer. Moving that data into tables specifically for that customer is one way to reduce data usage in BigQuery.

**Comment by joker1007** [comment]
Thank you for comments.
master branch of fluent-plugin-bigquery (released as v0.5.0.beta) has already supported this feature. Because fluentd-0.14.x can use any keys as buffer chunk key, and this plugin supports the feature.
But on fluentd-0.12, it is not easy to support dynamic name assigning.
If this feature is very important, Please use fluentd-0.14.x and v0.5.0.beta.
